server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost/gnucash
    username: gnucash
    password: gnucash
  security:
    user:
      name: admin
      password: admin
security:
  ignored: /**