application:
  cors-origins: ${CORS_ORIGINS}
  jwt-duration-minutes: 10
  pagination:
    page.size: 10
    sort.direction: desc
    sort.field: postDate
  security:
    password: ${APP_SECURITY_PASSWORD}
    username: ${APP_SECURITY_USERNAME}
  google-auth:
    allowed-emails: ${GOOGLE_ALLOWED_EMAILS}
    redirect-url:
      success: ${GOOGLE_AUTH_SUCCESS_URL}
      failure: ${GOOGLE_AUTH_FAILURE_URL}

logging:
  level:
    root: info
rsa:
  private-key: ${RSA_PRIVATE_KEY_PATH}
  public-key: ${RSA_PUBLIC_KEY_PATH}
server:
  port: ${SERVER_PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    certificate: ${SSL_CERTIFICATE_PATH}
    certificate-private-key: ${SSL_PRIVATE_KEY_PATH}
spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email
