server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.102/gnucash
    username: gnucash
    password: gnucash

logging:
  level:
    root: info

security:
   username: fangi
   password: password

rsa:
  private-key: file:path/to/private/key
  public-key: file:path/to/public/key

app:
  default:
    page.size: 10
    sort.field: enterDate
    sort.direction: desc