cors:
  origins: http://192.168.1.5:4200
jwt:
  duration-minutes: 20
logging:
  level:
    root: info
pagination:
  page.size: 10
  sort.direction: desc
  sort.field: enterDate
rsa:
  private-key: file:/path/to/private/key
  public-key: file:/path/to/public/key
security:
  password: password
  username: fangi
server:
  port: 8087
spring:
  datasource:
    password: gnucash
    url: jdbc:postgresql://192.168.1.102/gnucash
    username: gnucash