server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost/gnucash2
    username: gnucash
    password: gnucash
  security:
    user:
      name: admin
      password: admin
security:
  ignored: /**
app:
  default:
    page.size: 10
    sort.field: description