application:
  cors-origins: http://localhost:4200
  jwt-duration-minutes: 20
  pagination:
    page.size: 10
    sort.direction: desc
    sort.field: enterDate
  security:
    password: password
    username: foo
  google-auth:
    allowed-emails: foo@foo.com
    redirect-url:
      success: http://localhost:4200/#/login?token=
      failure: http://localhost:4200/#/login?failed

logging:
  level:
    root: info
rsa:
  private-key: file:private.pem
  public-key: file:public.pem
server:
  port: 8089
  ssl:
    enabled: false
    certificate: file:fullchain.pem
    certificate-private-key: file:privkey.pem
spring:
  datasource:
    password: jfgk0fjk49s
    url: jdbc:postgresql://192.168.1.102/gnucash2
    username: gnucash
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
            scope: email
