server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.102/gnucash
    username: gnucash
    password: gnucash
  security:
    user:
      name: admin
      password: admin

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"

app:
  default:
    page.size: 10
    sort.field: enterDate
    sort.direction: desc