cors:
  origins: http://192.168.1.5:4200
jwt:
  duration-minutes: 20
logging:
  level:
    root: info
pagination:
  page.size: 10
  sort.direction: desc
  sort.field: enterDate
rsa:
  private-key: file:C:/Users/francesco.angi/certs/private.pem
  public-key: file:C:/Users/francesco.angi/certs/public.pem
security:
  password: password
  username: fangi
server:
  port: 8089
  ssl:
    enabled: false
    certificate: file:fullchain.pem
    certificate-private-key: file:privkey.pem
spring:
  datasource:
    password: jfgk0fjk49s
    url: jdbc:postgresql://192.168.1.102/gnucash2
    username: gnucash